apps/comments/urls.py
from django.urls import path
from apps.comments import views

app_name = 'comments'

urlpatterns = [
    # path('api-data/', views.comment_all_data, name='api-comment'),
    path('add-update-comment/', views.add_update_comment_view, name='add-update-comment'),
    path('delete-comment/', views.delete_comment, name='delete-comment'),
]

apps/profiles/urls.py
from django.urls import path
from apps.profiles import views

app_name = 'profiles'

urlpatterns = [
    # path('<int:id>/<str:firstname>', views.profile, name='profile'),
    path('<str:pseudo>/', views.profile, name='profile'),
    path('update', views.update_profile, name='update_profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from rest_framework import routers

from apps.notifications.api.urls import router as router_notifications

router = routers.DefaultRouter()
router.registry.extend(router_notifications.registry)


urlpatterns = [
    path('admin-site/mackind-administration', admin.site.urls, name='admin'),
    path('', include('apps.home.urls')),
    path('accounts/', include('apps.users.urls')),
    path('profile/', include('apps.profiles.urls')),
    path('feed/', include('apps.post.urls')),
    path('comment/', include('apps.comments.urls')),
    path('mynetwork/', include('apps.friends.urls')),
    path('notifications/', include('apps.notifications.urls')),
    
    # urls api
    # path('api/', include('apps.profiles.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('api/', include('apps.profiles.api.urls')),
        path('api/', include('apps.notifications.api.urls')),
        # path('api/', include(router.urls)),
        path('__debug__/', include(debug_toolbar.urls)),
    ]
else:
    urlpatterns += [re_path(r'^mediafiles/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),]

# print()
# print()
# for u in urlpatterns: 
#     print(u)
# print()
# print()

apps/comments/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from apps.post.models import Post

User = get_user_model()

class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='post_comment')
    message = models.CharField(max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    liked = models.ManyToManyField(User, related_name='users_comment_like', blank=True, default=None)
    
    def __str__(self):
        return f"Comment-{self.id}-{self.author.first_name}"

class ReponseComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_reponse_comment')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='reponse_comment')
    message = models.CharField(blank=True, null=True, max_length=500)
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return f"{self.author.first_name} {self.author.last_name}"

class LikeComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like_comment')
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='like_comment')
    LIKE_CHOICES = (
        ('Like', 'Like'),
        ('Unlike', 'Unlike'),
    )
    value = models.CharField(choices=LIKE_CHOICES, max_length=10)
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}   -   Comment Id: {self.post.id}"

apps/comments/forms.py
from django import forms
from django.forms import fields
from django.utils.translation import gettext_lazy as _

from apps.comments.models import Comment, ReponseComment


class CommentForm(forms.ModelForm):
    message = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'id':'input_message_comment_id', 'autocomplete': 'off', 'placeholder':'Ajouter un commentaire...'}))
    class Meta:
        model = Comment
        fields = ('message',)
    

class ReponseCommentForm(forms.ModelForm):
    message = forms.CharField(required=True, widget=forms.TextInput(
        attrs={'id':'input_message_reponse_comment_id', 'autocomplete': 'off', 'placeholder':'Ajouter une réponse...'}))
    class Meta:
        model = ReponseComment
        fields = ('message',)

apps/comments/views.py
import json
from datetime import datetime
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.contrib.humanize.templatetags.humanize import naturaltime

from apps.comments.models import Comment, ReponseComment, LikeComment
from apps.comments.forms import CommentForm, ReponseCommentForm

User = get_user_model()


def comment_view(request):
    qs_comment = Comment.objects.all()
    form_comment = CommentForm(request.POST)
    form_reponse = ReponseCommentForm(request.POST)
    
    context = {
        'qs_comment': qs_comment,
        'form_comment': form_comment,
        'form_reponse': form_reponse
    }
    return context


@login_required(login_url='sign_in')
def comment_all_data(request):  
    qs_comment = Comment.objects.select_related("author").select_related("post").all()
    qs_user = User.objects.prefetch_related("profile")
    
    data = []
    
    for obj in qs_comment:
        item = {
            'id': obj.id,
            'comment_author': obj.author.email,
            'comment_author_id': obj.author.id,
            'comment_message': obj.message,
            'comment_date_added': naturaltime(obj.date_added),
            'post_id': obj.post.id,
            'post_author': obj.post.author.email,
            'post_message': obj.post.message,
            'post_img': obj.post.img.url,
            'user_img_bio': qs_user.get(id=obj.author.id).profile.bio,
            'user_img_profile': qs_user.get(id=obj.author.id).profile.img_profile.url,
            'current_user': request.user.email,
        }
        data.append(item)
  
    return JsonResponse({'data': data})


@login_required(login_url='sign_in')
def add_update_comment_view(request):
    user = request.user
    
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        # print('\n\najax request with fetch')
        
        don = json.load(request)
        
        message = don['message'] 
        id_post = don['id_post'] 
        id_comment = don['id_comment'] 
        
        if id_comment:
            if Comment.objects.filter(id=id_comment).exists():
                comment_post = Comment.objects.get(id=id_comment)
                comment_post.message = message
                comment_post.save()
        else:
            comment_post = Comment.objects.create(author=user, post_id=id_post, message=message)
        
        data = {
            'id': comment_post.id,
            'comment_author': comment_post.author.email,
            'comment_author_first_name': comment_post.author.first_name,
            'comment_author_last_name': comment_post.author.last_name,
            'comment_message': comment_post.message,
            'comment_date_added': naturaltime(comment_post.date_added),
            
            'post_author': comment_post.post.author.email,
            'post_id': comment_post.post.id,
            
            'user_profile_bio': comment_post.author.profile.bio,
            'user_profile_img': comment_post.author.profile.img_profile.url if comment_post.author.profile.img_profile else "",
            
            'current_user': request.user.email
        }
        
        return JsonResponse(data, status=200)


@login_required(login_url='sign_in')
def delete_comment(request):
    id_comment = request.POST.get("id_comment")
    obj = Comment.objects.get(id=id_comment)
    obj.delete()
    return JsonResponse({'action': "commentaire supprimer"})

templates/comments/include/ajax_comment.html
{% load static %}

<script>

  // $(document).ready(function () {
  //     $(".form-comment").submit(function (e) {
  //         e.preventDefault();

  //         const post_id = $(this).attr("title");
  //         const url = $(this).attr("action");

  //         const aside_comment = $(`#aside-comment-${post_id}`);
  //         const input_text_comment = $(`#input_message_comment-${post_id}`);
  //         const input_hidden_post_comment = $(
  //             `#input_hidden_post_comment-${post_id}`
  //         );

  //         // console.log($(`.form-comment > input[name=csrfmiddlewaretoken]`).val());
  //         console.log("{{csrf_token}}");
  //         console.log(input_hidden_post_comment.val());
  //         console.log(input_text_comment.val());
  //         console.log(url);

  //         $.ajax({
  //             type: "POST",
  //             url: url,
  //            
  //             data: {
  //                 // 'csrfmiddlewaretoken': $(`.form-comment > input[name=csrfmiddlewaretoken]`).val(),
  //                 "csrfmiddlewaretoken": "{{csrf_token}}",
  //                 'post_id': input_hidden_post_comment.val(),
  //                 'message': input_text_comment.val(),
  //             },
  //             success: function (response) {
  //                 const data = JSON.parse(JSON.stringify(response.data[0]));
  //                 console.log(data);
  //                 console.log(data.comment_author);
  //                 input_text_comment.val("");

  //                 // function verif_img(v) {
  //                 //     if (v) {
  //                 //         return `<img id="container-comment-list-img-profile" src="http://127.0.0.1:8000${v}" />`;
  //                 //     } else {
  //                 //         return `<img id="container-comment-list-img-profile" src="http://127.0.0.1:8000/static/components/img/user.svg" />`;
  //                 //     }
  //                 // }

  //                 // function verif_author(author_comment, author_post) {
  //                 //     if (author_comment === author_post) {
  //                 //         return `<span id="author_post_and_comment">Auteur</span>`;
  //                 //     }
  //                 // }

  //                 // content_comment = `<div class="container-comment-list">
  //                 //     ${verif_img(data.user_profile_img)}
  //                 //           <div class="comment-content-box">
  //                 //           <div class="comment-info-content">
  //                 //               <div class="comment-info-content-I">
  //                 //               <strong>${data.comment_author_first_name}
  //                 //               ${data.comment_author_last_name}
  //                 //               ${verif_author(data.comment_author, data.post_author)}

  //                 //               </strong>
  //                 //               <small>${data.comment_date_added}</small>
  //                 //               </div>
  //                 //               <p id="comment-author-profile-title">${data.user_profile_bio
  //                 //                 }</p>
  //                 //           </div>
  //                 //           <div class="comment-text-content">
  //                 //               <p>${data.comment_message}</p>
  //                 //           </div>
  //                 //           </div>
  //                 //       </div>
  //                 //   `;

  //                 //             aside_comment.append(content_comment);
  //             },
  //             error: function (error) {
  //                 console.log(error);
  //             },
  //             cache: false,
  //             contentType: false,
  //             processData: false,
  //         });
  //     });
  // });


  const form_comments = document.querySelectorAll(".form-comment-list-input-container-global");

  form_comments.forEach(form => {
    form.addEventListener("submit", (e) => {

      const input_text_comment = document.getElementById("input_message_comment-" + e.target.title).value;
      const input_hidden_post_comment = document.getElementById("input_hidden_post_comment-" + e.target.title).value;
      // alert(`${input_text_comment} - ${input_hidden_post_comment}`)
      const container_list_comment = document.getElementById("container-global-comment-list-" + e.target.title);
      e.preventDefault()

      function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
          const cookies = document.cookie.split(';');
          for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
              cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
              break;
            }
          }
        }
        return cookieValue;
      }
      const csrftoken = getCookie('csrftoken');

      // async function loadComments() {
      //     const res = await fetch("{% url 'post_list' %}", {
      //         method: 'POST',
      //         credentials: 'same-origin',
      //         headers: {
      //             'Accept': 'application/json',
      //             'X-Requested-With': 'XMLHttpRequest',
      //             'X-CSRFToken': csrftoken,
      //         },
      //         body: JSON.stringify({ 'message': input_text_comment, 'id_post': input_hidden_post_comment })
      //     })

      //     const data = await JSON.parse(res.json());
      //     const data1 = await data.comment_author;

      //     return data
      // }

      // let d = [];

      // try {
      //     d = loadComments();
      // } catch (e) {
      //     console.log(e);
      // }

      // console.log(d);

      fetch("{% url 'post_list' %}", {
        method: 'POST',
        credentials: 'same-origin',
        headers: {
          'Accept': 'application/json',
          'X-Requested-With': 'XMLHttpRequest',
          'X-CSRFToken': csrftoken,
        },
        body: JSON.stringify({ 'message': input_text_comment, 'id_post': input_hidden_post_comment })
      })
        .then(response => {
          return response.json();
        }
        )
        .then(data => {
          console.log(data);
          console.log(data.comment_message);


          const verif_img = (v) => {
            if (v) {
              return `<img id="container-comment-list-img-profile" src="http://127.0.0.1:8000${v}" />`;
            } else {
              return `<img id="container-comment-list-img-profile" src="http://127.0.0.1:8000/static/components/img/user.svg" />`;
            }
          };

          const verif_author = (author_comment, author_post) => {
            if (author_comment === author_post) {
              return `<span id="author_post_and_comment">Auteur</span>`;
            } else {
              return "";
            }
          };
          // 
          // 

          container_list_comment.innerHTML += `
            <div class="container-comment-list">
              ${verif_img(data.user_profile_img)}              <div class="comment-content-box">
                <div class="comment-info-content">
                  <div class="comment-info-content-I">
                    <strong>${data.comment_author_first_name}
                      ${data.comment_author_last_name}
                      ${verif_author(data.comment_author, data.post_author)}
                    </strong>
                    <small>${data.comment_date_added}</small>
                  </div>
                  <p id="comment-author-profile-title">${data.user_profile_bio}</p>
                </div>
                <div class="comment-text-content">
                  <p>${data.comment_message}</p>
                </div>
              </div>
            </div>`;
        })
      document.getElementById("input_message_comment-" + e.target.title).value = ""

    })
  });
</script>

templates/comments/include/comment.html
{% load static %}
{% load humanize %}
{% load cloudinary %}

<form title="{{post.id}}"
  class="form-comment-list-input-container-global {% if not post_detail %} D-none_V-hidden_O-0 {% endif %}"
  id="form-comment-list-input-container-global{{post.id}}" method="post"
  action="{% url 'comments:add-update-comment' %}">
  <div class="form-comment-container-input">
    {% csrf_token %}
    <div class="form-content-comment">
      <img src="        
        {% if user.profile.img_profile %}
        {{ user.profile.img_profile.url }}
        {% else %}
        {% static 'profiles/img/default-img-profile.jpg' %}
        {% endif %}" />
      <!-- {{form_comment.message}} -->
      <input type="text" name="message" id="input_message_comment-{{post.id}}" class="input_message_comment_id"
        autocomplete="off" placeholder="Ajouter un commentaire..." required>
      <input type="hidden" name="post_id_comment" id="input_hidden_post_comment-{{post.id}}" value="{{post.id}}">
      <input type="hidden" name="post_id_comment2" id="input_hidden_post_comment2-{{post.id}}" value="">
    </div>
    <button class="btn-send-comment" type="submit" name="submit_c_form" title="{{post.id}}">Envoyer</button>
  </div>

  <div class="container-global-comment-list" id="container-global-comment-list-{{post.id}}">
    {% for comment in post.post_comment.all %}
    <div class="container-comment-list" id="container-comment-list{{comment.id}}">
      {% include 'comments/include/comment_opts.html' %}
      <a href="{% url 'profiles:profile' pseudo=comment.author.profile.pseudo  %}">
        <img id="container-comment-list-img-profile" src="        
      {% if comment.author.profile.img_profile %}
      {{ comment.author.profile.img_profile.url }}
      {% else %}
      {% static 'profiles/img/default-img-profile.jpg' %}
      {% endif %}" /></a>
      <div class="comment-content-box">
        <div class="comment-info-content">
          <div class="comment-info-content-I" id="comment-info-content-I-{{post.id}}">
            <strong>
              <a href="{% url 'profiles:profile' pseudo=comment.author.profile.pseudo  %}">{{comment.author.first_name}}
                {{comment.author.last_name}}
              </a>
              {% ifequal comment.author comment.post.author %}
              <span id="author_post_and_comment">Auteur</span>
              {% endifequal %}
            </strong>
            <p id="comment-author-profile-title">{{ comment.author.profile.bio }}</p>
          </div>
          <small>{{ comment.date_added|naturaltime }}</small>
        </div>
        <div class="comment-text-content">
          <p class="msg-text-p-{{comment.id}}" id="{{post.id}}">{{ comment.message }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>

  <div class="container-comment-like">
    <!-- <img src="{% static 'comments/img/like.svg' %}" alt=""> -->
  </div>
</form>

templates/comments/include/comment_opts.html
{% load static %}

{% ifequal request.user comment.author %}
<div id="{{comment.id}}" class="comment-options-btn">
  <span id="btn-point"></span>
  <span id="btn-point"></span>
  <span id="btn-point"></span>
</div>

<div id="comment-options-container{{comment.id}}" class="comment-options-actions-container display-none">
  <ul>
    <div class="comment-options-item comment-options-item-edit" id="{{comment.id}}">
      <img src="{% static 'comments/img/edit.svg' %}" id="{{comment.id}}" class="comment-options-item-img">
      <span class="btn-edit-comment comment-options-item-span" id="{{comment.id}}">Modifier</span>
    </div>

    <div class="comment-options-item comment-options-item-delete" id="{{comment.id}}" title="{{post.id}}">

      <img src="{% static 'comments/img/delete.svg' %}" id="{{comment.id}}" class="comment-options-item-img">
      <span class="btn-del-comment comment-options-item-span" id="{{comment.id}}" title="{{post.id}}">Supprimer</span>
    </div>
  </ul>
</div>
{% endifequal %}