apps/friends/urls.py
from django.urls import path
from apps.friends import views

app_name = 'friends'

urlpatterns = [
    path('', views.invites_list_profiles_view, name='my_network'),
    path('connections/', views.my_friends_invites_profiles_view, name='my_friends'),
    path('invitation-received/', views.invites_received_view, name='invitation_received'),
    path('invitation-send/', views.invites_sended_view, name='invitation_send'),
    
    path('invitation/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitation/reject/', views.reject_invitation, name='reject_invitation'),
    path('invitation/cancel/', views.cancel_invitation, name='cancel_invitation'),
    
    path('invitation/send', views.send_invitation, name='send_invitation'),
    path('invitation/remove', views.remove_from_friends, name='remove_invitation'),
]

apps/profiles/api/urls.py
from django.urls import path

from apps.profiles.api import views

app_name = 'api-profiles'

urlpatterns = [
    path('profiles/', views.get_list_profiles),
    path('profiles/<int:id>/', views.get_profile),
]

apps/profiles/urls.py
from django.urls import path
from apps.profiles import views

app_name = 'profiles'

urlpatterns = [
    # path('<int:id>/<str:firstname>', views.profile, name='profile'),
    path('<str:pseudo>/', views.profile, name='profile'),
    path('update', views.update_profile, name='update_profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from rest_framework import routers

from apps.notifications.api.urls import router as router_notifications

router = routers.DefaultRouter()
router.registry.extend(router_notifications.registry)


urlpatterns = [
    path('admin-site/mackind-administration', admin.site.urls, name='admin'),
    path('', include('apps.home.urls')),
    path('accounts/', include('apps.users.urls')),
    path('profile/', include('apps.profiles.urls')),
    path('feed/', include('apps.post.urls')),
    path('comment/', include('apps.comments.urls')),
    path('mynetwork/', include('apps.friends.urls')),
    path('notifications/', include('apps.notifications.urls')),
    
    # urls api
    # path('api/', include('apps.profiles.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('api/', include('apps.profiles.api.urls')),
        path('api/', include('apps.notifications.api.urls')),
        # path('api/', include(router.urls)),
        path('__debug__/', include(debug_toolbar.urls)),
    ]
else:
    urlpatterns += [re_path(r'^mediafiles/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),]

# print()
# print()
# for u in urlpatterns: 
#     print(u)
# print()
# print()

apps/profiles/models.py
import os
from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
from cloudinary.models import CloudinaryField

User = get_user_model()
from apps.profiles.managers import ProfileManager


def rename_img(instance, filename):
    upload_to = 'image_profile'
    ext = filename.split('.')[-1]
    filename = f"{instance.user.first_name}_{instance.user.pk}_{instance.date_updated.strftime('%d-%m-%Y %H%M%S')}.{ext}"
    folder = f"{instance.user.first_name}_{instance.user.pk}"
    return os.path.join('media', folder, upload_to, filename)

def pseudo_rename(instance, filename):
    upload_to = 'image_profile'
    ext = filename.split('.')[-1]
    filename = f"{instance.user.first_name}_{instance.user.pk}_{instance.date_updated}.{ext}"
    return os.path.join(upload_to, filename)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    pseudo = models.CharField(_("non d'utilisateur"), max_length=48, blank=True, unique=True)
    bio = models.CharField(_("titre du profil"), max_length=250, blank=True)
    # img_profile = models.ImageField(_("photo de profile"), upload_to=rename_img, default='default/default-img-profile.jpg', blank=True, null=True)
    # img_bg = models.ImageField(_("photo de couverture"), upload_to=rename_img, default='default/default-img-bg.jpg', blank=True, null=True)
    img_profile = CloudinaryField('photo de profile', blank=True, null=True, default="https://res.cloudinary.com/dm68aag3e/image/upload/v1649743168/default-img-profile_hrhx6z.jpg")
    img_bg = CloudinaryField('photo de couverture', blank=True, null=True, default="https://res.cloudinary.com/dm68aag3e/image/upload/v1649743327/default-img-bg_zbeoo4.jpg")
    birth_date = models.DateField(_("date de naissence"), null=True, blank=True)
    
    class GenderChoices(models.TextChoices):
        male = 'M', _('Masculin')
        female = 'F', _('Féminin')
    
    gender = models.CharField(_("sexe"), max_length=1, blank=True, choices=GenderChoices.choices)
    phone = models.CharField(_("téléphone"), max_length=20, blank=True)
    adress = models.CharField(_("adresse"), max_length=128, blank=True)
    town = models.CharField(_("ville"), max_length=68, blank=True)
    region = models.CharField(_("région"), max_length=68, blank=True)
    zipcode = models.CharField(_("code postal"), max_length=22, blank=True)
    country = models.CharField(_("pays"), max_length=45, blank=True)
    description = models.TextField(_("description"), blank=True)
    link_linkedin = models.URLField(_("lien de votre profile linkedin"), blank=True)
    link_gitthub = models.URLField(_("lien de votre profile gitthub"), blank=True)
    link_twitter = models.URLField(_("lien de votre twitter"), blank=True)
    link_mysite = models.URLField(_("lien de votre de site web"), blank=True)
    number_views = models.IntegerField(_('Nombre de vue profil'), default=0, blank=True, null=True)
    friends = models.ManyToManyField(User, blank=True, related_name='friends')    
    date_updated = models.DateTimeField(_("date de modification"), auto_now=True)
    
    objects = ProfileManager()
    
    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    
    def get_friends(self):
        return self.friends.all()
    
    def get_number_friends(self):
        return self.friends.all().count()
    
    class Meta:
        verbose_name = _('Profile')
        verbose_name_plural = _('Profiles')
    

apps/profiles/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model

from apps.profiles.models import Profile

User = get_user_model()

class ProfileForm(forms.ModelForm):
    # img_profile = forms.ImageField(required=False, widget=forms.FileInput(
    #     attrs={'class':'form-control-profile'}))
    # img_bg = forms.ImageField(required=False, widget=forms.FileInput(
    #     attrs={'class':'form-control-profile'}))
    # img_profile_clear = forms.BooleanField(required=False, widget=forms.CheckboxInput(
    #     attrs={'class':'form-control-profile'}))
    class Meta:
        model = Profile
        exclude = ('user', 'number_views', 'gender', 'birth_date', 'friends',)
        widgets = {
            'pseudo': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'bio': forms.TextInput(attrs={'class': 'form-control-profile'}),
            # 'img_profile': forms.FileInput(attrs={'class': 'form-control-profile'}),
            # 'img_bg': forms.FileInput(attrs={'class': 'form-control-profile'}),
            'phone': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'adress': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'town': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'region': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'zipcode': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'country': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'description': forms.Textarea(attrs={'cols':'80', 'rows':'8', 'class': 'form-control-profile'}),
            'link_linkedin': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'link_gitthub': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'link_twitter': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'link_mysite': forms.TextInput(attrs={'class': 'form-control-profile'}),
        }
        
class UserProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name',)
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control-profile'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control-profile'}),

        }
        

apps/profiles/api/views.py
from django.shortcuts import get_object_or_404

from rest_framework.decorators import api_view
from rest_framework.response import Response
from apps.comments.models import Comment
from apps.post.models import Post

from apps.profiles.api.serializers import ProfileSerializer
from apps.profiles.models import Profile


@api_view()
def get_list_profiles(request):
    qs = Profile.objects.select_related('user').all()
    serializers = ProfileSerializer(qs, many=True)
    # print("IP Address for debug-toolbar: " + request.META['REMOTE_ADDR'])
    return Response(serializers.data)


@api_view()
def get_profile(request, id):
    qs = get_object_or_404(Profile, pk=id)
    serializer = ProfileSerializer(qs)
    # print(serializer.data)
    return Response(serializer.data)

apps/profiles/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

User = get_user_model()
from apps.profiles.models import Profile
from apps.profiles.forms import ProfileForm, UserProfileForm
from apps.friends.views import list_relation_receiver_and_sender

@login_required(login_url='sign_in')
def profile(request, pseudo):
    profile = get_object_or_404(Profile, pseudo=pseudo)
    if request.user != profile.user:
        profile.number_views = profile.number_views + 1
        profile.save()
    
    template = "profiles/profiles.html"
    t, context = list_relation_receiver_and_sender(request)
    context.update(
        {
            'profile': profile,
        }
    )
    return render(request, template, context=context)


@login_required(login_url='sign_in')
def update_profile(request):
    user = request.user
    user_profile_form = UserProfileForm(instance=user)
    profile_form = ProfileForm(instance=user.profile)
    
    if request.method == 'POST':
        user_profile_form = UserProfileForm(request.POST, instance=user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if profile_form.is_valid() and user_profile_form.is_valid():
            user_profile_form.save()
            profile_form.save()
            return redirect('profiles:profile', pseudo=user.profile.pseudo)
    
    template = "profiles/update.html"
    context = {
        'user_profile_form' : user_profile_form,
        'profile_form' : profile_form,
    }
    return render(request, template, context=context)

templates/profiles/profiles.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load cloudinary %}


{% block title %} {{profile.user.first_name}} {{profile.user.last_name}} {% endblock title %}


{% block style %}
<link rel="shortcut icon" href=" {% static 'components/img/linkedin-cust.svg' %} " type="image/x-icon">
<link rel="stylesheet" href=" {% static 'components/css/style.css' %}" />
<link rel="stylesheet" href=" {% static 'profiles/css/style.css' %} " />
{% endblock style %}

<!-- Navbar -->
{% block navbar %} {% include 'components/navbar2.html' %} {% endblock navbar %}

{% block content %}
<main class="main-profile">
  <div class="container-left">
    <section class="profile-info">
      <div class="container-info">
        <div class="info-img-bg">
          <img class="img_bg" src="
              {% if profile.img_bg %}
                {{ profile.img_bg.url }}
              {% else %}
                {% static 'profiles/img/default-img-bg.jpg' %}
              {% endif %}" alt="Couverture">
        </div>
        <img class="img_profile" src="{% if profile.img_profile %}
          {{ profile.img_profile.url }}
          {% else %}
          {% static 'profiles/img/default-img-profile.jpg' %}
          {% endif %}" alt="Profile">
        <div class="info-content">
          <h2>{{profile.user.first_name}} {{profile.user.last_name}} <span id="point-separator-style"></span>
            <small>@{{profile.pseudo}}</small>
          </h2>
          <p>{{profile.bio}}</p>

          {% if profile.country or profile.region or profile.town %}
          <div class="box-location">
            <img src="{% static 'profiles/img/location.svg' %}">
            <p>
              {% if profile.country %}
              {{profile.country|title}}
              <span id="point-separator-style"></span>
              {% endif %}

              {% if profile.region %}
              {{profile.region|title}}
              <span id=" point-separator-style"></span>
              {% endif %}
              {{profile.town|title}}
            </p>
          </div>
          {% endif %}

          {% if profile.user.email %}
          <div class="box-tel">
            <img src="{% static 'profiles/img/email.svg' %}">
            <p> {{profile.user.email}} </p>
          </div>
          {% endif %}

          {% if profile.phone %}
          <div class="box-tel">
            <img src="{% static 'profiles/img/phone.svg' %}">
            <p>{{profile.phone}}</p>
          </div>
          {% endif %}

          <div class="box-friends">
            <img src="{% static 'profiles/img/friends.svg' %}">

            {% if profile.user == request.user %}
            <a href="{% url 'friends:my_friends' %}">
              {{profile.friends.count}}
              {% if profile.friends.count > 1 %}
              relations
              {% else %}
              relation
              {% endif %}
            </a>
            {% else %}
            <p>
              {{profile.friends.count}}
              {% if profile.friends.count > 1 %}
              relations
              {% else %}
              relation
              {% endif %}
            </p>
            {% endif %}
          </div>

          {% if profile.user == request.user %}
          <!-- <div class="btn-container-update-profile"> -->
          <a class="btn-container-update-profile" href="{% url 'profiles:update_profile' %}">Modifier le profile</a>
          <!-- </div> -->
          {% endif %}

          {% if profile.user not in list_receiver and profile.user not in list_sender and user != profile.user %}
          <form action="{% url 'friends:send_invitation' %}" method="POST" class="to-invites-add-friends">
            {% csrf_token %}
            <input type="hidden" name="profile_id" value="{{profile.id}}">
            <input type="hidden" name="redirect" value="profile">
            <button class="btn-add-friends" type="submit">Envoyer une invitation</button>
          </form>
          {% endif %}


          {% comment %}
          {% if request.user in profile.friends.all %}
          <!-- <form action="{% url 'friends:remove_invitation' %}" method="POST" class="to-invites-add-friends">
            {% csrf_token %}
            <input type="hidden" name="profile_id" value="{{profile.id}}">
            <input type="hidden" name="redirect" value="profile">
            <button class="btn-remove-friends" type="submit">Supprimer</button>
          </form> -->
          {% endif %}
          {% endcomment %}

        </div>
      </div>
    </section>

    <section class="profile-description">
      <h2>Infos</h2>
      <div class="container-description">
        <p>
          {{ profile.description|linebreaksbr }}
        </p>
      </div>
    </section>
  </div>

  <div class="container-right">
    <aside class="asd-info-stat">
      {% if profile.user == request.user %}
      <!-- <div class="btn-container-update-profile">
        <a href="{% url 'profiles:update_profile' %}">Modifier le profile</a>
      </div> -->
      {% endif %}

      <div class="statistic-profile">
        <div class="num-vue statistic">
          <span class="statistic-text">Vues de votre profile</span>
          <span class="statistic-num">
            {% if profile.number_views %}
            {{profile.number_views}}
            {% else %}
            0
            {% endif %}
          </span>
        </div>
        <div class="num-post statistic">
          <span class="statistic-text">Nombre de post</span>
          <span class="statistic-num">{{profile.user.post.count}}</span>
        </div>
      </div>
      <div class="others-link">

        {% if profile.link_linkedin %}
        <div class="link-pro">
          <img src="{% static 'components/img/linkedin.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_linkedin}}" class="link-pro-link" target="_blank">linkedin</a>
        </div>
        {% endif %}

        {% if profile.link_twitter %}
        <div class="link-pro">
          <img src="{% static 'components/img/twitter.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_twitter}}" class="link-pro-link" target="_blank">twitter</a>
        </div>
        {% endif %}

        {% if profile.link_gitthub %}
        <div class="link-pro">
          <img src="{% static 'components/img/github.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_gitthub}}" class="link-pro-link" target="_blank">github</a>
        </div>
        {% endif %}

        {% if profile.link_mysite %}
        <div class="link-pro">
          <img src="{% static 'profiles/img/web.svg' %}" class="link-pro-icon">
          <a href="{{profile.link_mysite}}" class="link-pro-link" target="_blank">mysite</a>
        </div>
        {% endif %}
      </div>
    </aside>

    {% if profile.friends.all|length >= 1 %}
    <aside class="asd-rs">
      <div class="profile-friends-box-container">
        <h4>Vos Relations</h4>
        <div class="profile-friends-container">
          {% for obj in profile.friends.all|slice:"5" %}
          <a href="{% url 'profiles:profile' pseudo=obj.profile.pseudo %}">
            <div class="profile-friends-box">
              <img class="profile-img-friends" src="{% if obj.profile.img_profile %}
            {{ obj.profile.img_profile.url }}
            {% else %}
            {% static 'profiles/img/default-img-profile.jpg' %}
            {% endif %}">

              <div class="profile-friends-info-container">

                <strong>{{obj.first_name}} {{obj.last_name}}</strong>
                <p>{{obj.profile.bio}}</p>

                {% if obj.last_logout %}
                <P>
                  {% if obj.last_logout > obj.last_login %}
                  Connecté {{obj.last_logout|naturaltime}}
                  {% else %}
                  Connecté maintenant
                  {% endif %}
                </P>
                {% endif %}
              </div>
            </div>
          </a>
          {% endfor %}
        </div>

        {% if profile.friends.all|length > 5 %}
        <div class="voir-plus-box">
          <a href="{% url 'friends:my_friends' %}" class="voir-plus">Voir plus</a>
        </div>
        {% endif %}
      </div>
    </aside>
    {% endif %}
  </div>
</main>
{% endblock content %}

<!-- Footer -->
{% block footer %} {% include 'components/footer.html' %} {% endblock footer %}

{% block js %}
<script type="text/javascript" src=" {% static 'components/js/index.js' %} "></script>
<script type="text/javascript" src=" {% static 'notifications/js/notifications.js' %} "></script>
{% endblock js %}

templates/profiles/update.html
{% extends 'base.html' %}
{% load static %}
{% load cloudinary %}


{% block title %} Update profile {{profile.user.first_name}} {{profile.user.last_name}} {% endblock title %}


{% block style %}
<link rel="shortcut icon" href=" {% static 'components/img/linkedin-cust.svg' %} " type="image/x-icon">
<link rel="stylesheet" href=" {% static 'components/css/style.css' %}" />
<link rel="stylesheet" href=" {% static 'profiles/css/style.css' %} " />
{% endblock style %}

<!-- Navbar -->
{% block navbar %} {% include 'components/navbar2.html' %} {% endblock navbar %}

{% block content %}
<main class="main-profile-update">

  <div class="update-porfile-container">
    <h2>Modifier le profile</h2>

    <form action="" method="POST" enctype="multipart/form-data" class="form-profile-update">
      {% csrf_token %}

      {% for field in user_profile_form %}
      <div class="container-form-control-profile">
        <label for="id_{{field.name}}">{{field.label}}</label>
        {{field}}
      </div>
      {% endfor %}

      {% for field in profile_form %}
      <div class="container-form-control-profile">
        <label for="id_{{field.name}}">{{field.label}}</label>
        {{field}}
      </div>
      {% endfor %}

      <input type="submit" value="Enregistrer">
    </form>
  </div>

</main>
{% endblock content %}

<!-- Footer -->
{% block footer %} {% include 'components/footer.html' %} {% endblock footer %}

{% block js %}
<script type="text/javascript" src=" {% static 'components/js/index.js' %} "></script>
<script type="text/javascript" src=" {% static 'notifications/js/notifications.js' %} "></script>
{% endblock js %}