apps/friends/urls.py
from django.urls import path
from apps.friends import views

app_name = 'friends'

urlpatterns = [
    path('', views.invites_list_profiles_view, name='my_network'),
    path('connections/', views.my_friends_invites_profiles_view, name='my_friends'),
    path('invitation-received/', views.invites_received_view, name='invitation_received'),
    path('invitation-send/', views.invites_sended_view, name='invitation_send'),
    
    path('invitation/accept/', views.accept_invitation, name='accept_invitation'),
    path('invitation/reject/', views.reject_invitation, name='reject_invitation'),
    path('invitation/cancel/', views.cancel_invitation, name='cancel_invitation'),
    
    path('invitation/send', views.send_invitation, name='send_invitation'),
    path('invitation/remove', views.remove_from_friends, name='remove_invitation'),
]

apps/home/urls.py
from django.urls import path
from apps.home import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

apps/post/urls.py
from apps.post import views
from django.urls import path

app_name = 'post'

urlpatterns = [
    path('', views.post_create_list_view, name='post_list'),
    path('<int:post_id>/', views.post_detail_view, name='post_detail'),
    # path('add-post/', views.add_post, name='add_post'),
    path('<int:post_id>/delete-post/', views.delete_post, name='delete_post'),
    path('<int:post_id>/update-post/', views.update_post, name='update_post'),
    path('like/', views.like_post, name='like_post'),
]

apps/profiles/urls.py
from django.urls import path
from apps.profiles import views

app_name = 'profiles'

urlpatterns = [
    # path('<int:id>/<str:firstname>', views.profile, name='profile'),
    path('<str:pseudo>/', views.profile, name='profile'),
    path('update', views.update_profile, name='update_profile'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

from rest_framework import routers

from apps.notifications.api.urls import router as router_notifications

router = routers.DefaultRouter()
router.registry.extend(router_notifications.registry)


urlpatterns = [
    path('admin-site/mackind-administration', admin.site.urls, name='admin'),
    path('', include('apps.home.urls')),
    path('accounts/', include('apps.users.urls')),
    path('profile/', include('apps.profiles.urls')),
    path('feed/', include('apps.post.urls')),
    path('comment/', include('apps.comments.urls')),
    path('mynetwork/', include('apps.friends.urls')),
    path('notifications/', include('apps.notifications.urls')),
    
    # urls api
    # path('api/', include('apps.profiles.api.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    import debug_toolbar
    urlpatterns += [
        path('api/', include('apps.profiles.api.urls')),
        path('api/', include('apps.notifications.api.urls')),
        # path('api/', include(router.urls)),
        path('__debug__/', include(debug_toolbar.urls)),
    ]
else:
    urlpatterns += [re_path(r'^mediafiles/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),]

# print()
# print()
# for u in urlpatterns: 
#     print(u)
# print()
# print()

templates/components/footer.html
{% load static %}

<footer>
  <div class="footer-content">
    <div class="footer-content-box">
      <a class="footer-logo" href="{% url 'home:home' %}">
        <img src="{% static 'components/img/logo3.jpg' %}" alt="logo Macktireh">
      </a>
    </div>

    <div class="footer-content-box ul-container">
      <ul>
        <li><a href="https://www.linkedin.com/in/macktireh/" target="_blank"><img
              src="{% static 'home/img/linkedin.svg' %}" alt="Compte linkedin"></a></li>
        <li><a href="https://github.com/Macktireh" target="_blank"><img class="ml"
              src="{% static 'home/img/github.svg' %}" alt="Compte github"></a>
        </li>
        <li><a href="https://twitter.com/macktireh" target="_blank"><img src="{% static 'home/img/twitter.svg' %}"
              alt="Compte twitter"></a>
        </li>
      </ul>
    </div>
  </div>
  <!-- <hr>    -->
  <div class="footer-bottom">
    <p>copyright &copy;2022 Macktireh Abdi Soubaneh | <a href="">Mentions légales</a></p>
  </div>
</footer>

templates/components/navbar-home.html
{% load static %}

<div class="nav-container">
  <div>
    <a class="logo" href="{% url 'home:home' %}" style="color: #1abc9c">
      Mackd<img src=" {% static 'components/img/linkedin-cust.svg' %} " alt="logo">
    </a>
  </div>
  <div>
    <nav style="padding-right: 30px">
      <ul class="nav-menu">
        {% if not user.is_authenticated %}
        <a href="{% url 'sign_in' %}" class="nav-item">
          <div class="nav-text">
            <img class="nav-img" src="{% static 'components/img/user.svg' %}" alt="">
            <span class="animation {% if start_animation == 'sign_in' %}start-animation{% endif %}"></span>
            <span class="nav-text-span">Connexion</span>
          </div>
        </a>
        <a href="{% url 'sign_up' %}" class="nav-item">
          <div class="nav-text">
            <img class="nav-img" src="{% static 'components/img/signup.svg' %}" alt="">
            <span class="animation {% if start_animation == 'sign_up' %}start-animation{% endif %}"></span>
            <span>S'inscrire</span>
          </div>
        </a>
        {% endif %}
      </ul>
    </nav>

    <div class="hamburger-nav-profil">
      <div class="hamburger">
        <span class="hamburger__bar"></span>
        <span class="hamburger__bar"></span>
        <span class="hamburger__bar"></span>
      </div>
    </div>
  </div>
</div>

templates/components/navbar.html
{% load static %}
<nav class="nav-bar">
  <a class="logo" href="{% url 'home' %}">
    <img src=" {% static 'home/img/logo.png' %} " alt="logo Macktireh">
  </a>

  <ul class="nav-menu">
    <li class="nav-item">
      <a class="nav-link" href="{% url 'home' %}">Home</a>
    </li>

    {% if user.is_authenticated %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}">Déconnexion</a>
    </li>
    {% if user.is_superuser %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'admin:index' %}" target="_blank">Administration</a>
    </li>
    {% endif %}
    {% else %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'sign_in' %}">S'identifier</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="{% url 'sign_up' %}">S'inscrire</a>
    </li>
    {% endif %}
  </ul>

  <div class="hamburger">
    <span class="hamburger__bar"></span>
    <span class="hamburger__bar"></span>
    <span class="hamburger__bar"></span>
  </div>
</nav>

templates/components/navbar2.html
{% load static %}
{% load cloudinary %}

<div class="nav-container">
  <div>
    <a class="logo" href="{% url 'home:home' %}">
      <img src=" {% static 'components/img/linkedin-cust.svg' %} " alt="logo">
    </a>
  </div>

  <nav>
    <ul class="nav-menu">
      {% if not user.is_authenticated %}
      <a href="{% url 'sign_in' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/user.svg' %}" alt="">
          <span class="animation {% if start_animation == 'sign_in' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">Connexion</span>
        </div>
      </a>
      <a href="{% url 'sign_up' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/signup.svg' %}" alt="">
          <span class="animation {% if start_animation == 'sign_up' %}start-animation{% endif %}"></span>
          <span>S'inscrire</span>
        </div>
      </a>
      {% else %}
      <a href="{% url 'post:post_list' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/home.svg' %}" alt="">
          <span class="animation  {% if start_animation == 'feed' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">Acceuil</span>
        </div>
      </a>
      <a href="{% url 'friends:my_network' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/friends.svg' %}" alt="">
          <span class="animation {% if start_animation == 'my_network' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">Réseau</span>
        </div>
      </a>
      <a href="" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/chat.svg' %}" alt="">
          <span class="animation {% if start_animation == 'chat' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">Messagerie</span>
        </div>
      </a>
      <a href="{% url 'notifications:notif' %}" class="nav-item nav-nofit" id="nav-nofit-icon">
        <span id="nav-nofit-alert"></span>
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/notification.svg' %}" alt="">
          <span class="animation {% if start_animation == 'notif' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">Notifications</span>
        </div>
      </a>
      {% if user.is_superuser %}
      <a href="{% url 'admin:index' %}" class="nav-item" target="_blank">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/contact.svg' %}" alt="">
          <span class="animation {% if start_animation == 'admin' %}start-animation{% endif %}}"></span>
          <span class="nav-text-span">Administration</span>
        </div>
      </a>
      {% endif %}
      <a href="{% url 'logout' %}" class="nav-item">
        <div class="nav-text">
          <img class="nav-img" src="{% static 'components/img/logout.svg' %}" alt="">
          <span class="animation {% if start_animation == 'logout' %}start-animation{% endif %}"></span>
          <span class="nav-text-span">Déconnexion</span>
        </div>
      </a>
      {% endif %}

      {% if user.is_authenticated %}
      <a href="{% url 'profiles:profile' pseudo=user.profile.pseudo  %}" class="nav-profil nav-profil-mobile">
        <div class="nav-box-profil">
          <img src="        
          {% if user.profile.img_profile %}
          {{ user.profile.img_profile.url }}
          {% else %}
          {% static 'components/img/user.svg' %}
          {% endif %}" alt="">
        </div>
      </a>
      {% endif %}
    </ul>
  </nav>

  <div class="hamburger-nav-profil">
    <div class="hamburger">
      <span class="hamburger__bar"></span>
      <span class="hamburger__bar"></span>
      <span class="hamburger__bar"></span>
    </div>

    {% if user.is_authenticated %}

    <a href="{% url 'profiles:profile' pseudo=user.profile.pseudo %}" class="nav-profil nav-profil-ecran">
      <div class="nav-box-profil">
        <img src="        
      {% if user.profile.img_profile %}
      {{ user.profile.img_profile.url }}
      {% else %}
      {% static 'components/img/user.svg' %}
      {% endif %}" alt="">
      </div>
    </a>
    {% endif %}
  </div>
</div>